### ISSUE TITLE
Reading bgeo and writing a different format : which struct to subclass ?

### ISSUE THREAD

**Issue by nyue** [dkoerner/hougeo#6]
Hi,

  I am writing a translator bgeo->obj

  Which struct should I subclass from ? Handler or Parser ? or something else ?

Cheers

**Comment by dkoerner** [comment]
Hi Nicholas,

you don't need to subclass anything. Just use the JSONReader to read the file into the json object model. This is done by using the parser like this:

	void import( std::istream *in )
	{
			json::JSONReader reader;
			json::Parser p;
			
			if(!p.parse( in, &reader ))
				throw std::runtime_error("parse failed");
			
			// now the reader contains the json data from the complete file
			// we access it via the root json object which we expect to be an array
			json::ArrayPtr root = reader.getRoot().asArray();
			
			// now we can start to query the json data for its content
			if( o->hasKey("pointcount") )
				std::cout << "#points:" << o->get<int>("pointcount", 0) << std::endl;
			if( o->hasKey("vertexcount") )
				std::cout << "#verts:" << o->get<int>("vertexcount", 0) << std::endl;
			if( o->hasKey("primitivecount") )
				std::cout << "#prims:" << o->get<int>("primitivecount", 0) << std::endl;
				
			// now parsing the file requires to know the schema of the layout which unfortunately
			// is not documented. The logger can be used to understand the schema of any given file.
	}


I will add some notes and an example.


Best,
Davod
