### ISSUE TITLE
Writing out .geo/.bgeo files

### ISSUE THREAD

**Issue by nyue** [dkoerner/hougeo#7]
Hi,

  Similar to the other question about translation bgeo->others, this question is about the inverse process.

  What struct should one use and is there going to be an example to illustrate how best to use HouGeo ?

Cheers

**Comment by dkoerner** [comment]
Hi Nicholas,

Let me just give you the example code straight away. It is pretty much straight forward:


		
	// Geometry is not part of hougeo. It is the geometry representation of the client code.
	void export( std::ostream *out, Geometry* geo, bool binary )
	{
		// we first instatiate a writer depending on wether we
		// want geo (ascii) or bgeo (binary) houdini files
		
		json::BinaryWriter *writer;
		if( binary )
			writer = new json::BinaryWriter( out );
		else
			// todo: ascii writer...
			writer = new json::BinaryWriter( out );
			
		// Now we use the writer to send the json data to the stream.
		// This requires knowledge about the json schema which unfortunately
		// is not documented. One can understand the schema by using the logger
		// on existing files. Note that the schema deviates in some places
		// between ascii and binary files.
		
		// the root node
		writer->jsonBeginArray();
		
			g_writer->jsonString( "pointcount" );
			g_writer->jsonInt( geo->pointcount() );

			g_writer->jsonString( "vertexcount" );
			g_writer->jsonInt( geo->vertexcount() );

			g_writer->jsonString( "primitivecount" );
			g_writer->jsonInt( geo->primitivecount() );
			
			// -- topology (required)
			g_writer->jsonString( "topology" );
			g_writer->jsonBeginArray();
				if( geo->getTopology() )
					exportTopology( geo->getTopology() );
			g_writer->jsonEndArray();
			
			// -- attributes
			g_writer->jsonString( "attributes" );
			g_writer->jsonBeginArray();

				// -- point attributes
				g_writer->jsonString( "pointattributes" );
				g_writer->jsonBeginArray();
					std::vector<std::string> pointAttrNames;
					geo->getPointAttributeNames(pointAttrNames);
					for( std::vector<std::string>::iterator it = pointAttrNames.begin(); it != pointAttrNames.end(); ++it )
						exportAttribute( geo->getPointAttribute(*it) );
				g_writer->jsonEndArray(); // pointattributes


				// -- primitive attributes
				g_writer->jsonString( "primitiveattributes" );
				g_writer->jsonBeginArray();
					std::vector<std::string> primitiveAttrNames;
					geo->getPrimitiveAttributeNames(primitiveAttrNames);
					for( std::vector<std::string>::iterator it = primitiveAttrNames.begin(); it != primitiveAttrNames.end(); ++it )
						exportAttribute( geo->getPrimitiveAttribute(*it) );
				g_writer->jsonEndArray(); // primitiveattributes

				// -- global attributes
				g_writer->jsonString( "globalattributes" );
				g_writer->jsonBeginArray();
					std::vector<std::string> globalAttrNames;
					geo->getGlobalAttributeNames(globalAttrNames);
					for( std::vector<std::string>::iterator it = globalAttrNames.begin(); it != globalAttrNames.end(); ++it )
						exportAttribute( geo->getGlobalAttribute(*it) );
				g_writer->jsonEndArray(); // globalattributes

			g_writer->jsonEndArray(); // attributes


			// -- primitives
			if( geo->primitivecount() > 0 )
			{
				g_writer->jsonString( "primitives" );
				g_writer->jsonBeginArray();
				for( int i=0;i<geo->primitivecount();++i )
				{
					HouGeoAdapter::Primitive::Ptr prim = geo->getPrimitive(i);

					if( std::dynamic_pointer_cast<HouGeoAdapter::VolumePrimitive>(prim) )
						exportPrimitive(std::dynamic_pointer_cast<HouGeoAdapter::VolumePrimitive>(prim));

				}
				g_writer->jsonEndArray(); // primitives
			}

		
		writer->jsonEndArray(); // /root
		
		delete writer;
	}

**Comment by dkoerner** [comment]
I realized there is a type in the code above when selecting the writer. Please check example_readwrite.cpp how it would be correct.
